const donorData = [
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"STEM",
      source:"Benevity",
      date:"23 Jan 2010",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"Anti-Violence",
      source:"Giving.sg",
      date:"12 Jun 2012",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"Anti-Violence",
      source:"Benevity",
      date:"12 Dec 2012",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"Anti-Violence",
      source:"Giving.sg",
      date:"12 Jan 2011",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"STEM",
      source:"Benevity",
      date:"12 Nov 2011",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"STEM",
      source:"Paypal",
      date:"12 Jun 2013",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"Anti-Violence",
      source:"Paypal",
      date:"30 Jun 2013",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"STEM",
      source:"Benevity",
      date:"12 Mar 2013",
    },
    {
      nric:"-",
      name:"Phua Chu Kang",
      amt:"$1000",
      campaign:"Anti-Violence",
      source:"Benevity",
      date:"11 Jun 2012",
    },
    {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Giving.sg",
        date:"1 Jul 2010",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Giving.sg",
        date:"1 Jun 2010",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"1 Apr 2013",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"2 Jun 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"9 Jun 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"7 Jun 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Giving.sg",
        date:"2 Apr 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"2 Oct 2018",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"8 Apr 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Giving.sg",
        date:"6 Jun 2015",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Benevity",
        date:"6 Jun 2016",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"6 Jun 2017",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Benevity",
        date:"2 Jun 2011",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"1 Jun 2012",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"3 Jun 2013",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Giving.sg",
        date:"10 Feb 2012",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"12 Sep 2017",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"10 Aug 2016",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"1 Nov 2018",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"12 May 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"12 Apr 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Giving.sg",
        date:"12 Mar 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"12 Feb 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Giving.sg",
        date:"12 Jan 2019",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Benevity",
        date:"1 Sep 2014",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Benevity",
        date:"20 Aug 2015",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Paypal",
        date:"12 Apr 2015",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Paypal",
        date:"12 Mar 2015",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"7 Feb 2015",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"30 Jun 2014",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Benevity",
        date:"8 Jun 2014",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"20 Jun 2016",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Giving.sg",
        date:"12 Jun 2015",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"20 Jul 2018",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"12 Dec 2016",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Paypal",
        date:"12 May 2016",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Giving.sg",
        date:"11 Jul 2017",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Giving.sg",
        date:"12 Jul 2017",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Paypal",
        date:"20 Jan 2018",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"Anti-Violence",
        source:"Benevity",
        date:"12 Jun 2017",
      },
      {
        nric:"-",
        name:"Phua Chu Kang",
        amt:"$1000",
        campaign:"STEM",
        source:"Benevity",
        date:"12 Jun 2019",
      }
  ]

export default donorData;